# Generated by Django 4.1.7 on 2023-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcut',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
